# While

In [1]:
error = 50
while error > 1:
    error = error / 4
    print(error)

12.5
3.125
0.78125


# For

In [2]:
# memanggil index dan valuenya menggunakan enumerate function
fam = [1.73, 1.68, 1.71, 1.89]

for index,height in enumerate(fam):
    print("index " + str(index) + ": " + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [3]:
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


# Dictionary
Dictionary bersifat unordered artinya tidak terurut

In [4]:
# memamnggil key dan value menggunakan items method
world = {
    "afghanistan":30.55,
    "albania":2.77,
    "algeria":39.21
}

for k,v in world.items():
    print(k + " -- " + str(v))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [5]:
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]

for data in house:
    print("the " + data[0] + " is " + str(data[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


# NumPy Arrays

In [6]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_weight / np_height ** 2

print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [7]:
for i in bmi: # bmi -> 1D array
    print(i)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [8]:
meas = np.array([np_height, np_weight]) # meas -> 2D array

for x in meas:
    print(x)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [9]:
# menggunakan nditer function untuk memanggil elemennya satu per satu
for i in np.nditer(meas):
    print(i)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


# Pandas DataFrame

In [10]:
import pandas as pd

brics = pd.read_csv("datasets/brics.csv", index_col=0) # index_col=0 berfungsi agar kolom pertamanya menjadi row label

# misal kita buat DataFrame melalui dictionary, maka kolomnya adalah key dictionary
for i in brics:
    print(i)

country
capital
area
population


In [11]:
# menggunakan iterrows method untuk memanggil label dan row data DataFrame
for lab,row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [12]:
# memanggil sub DataFrame yaitu capital
for lab,row in brics.iterrows():
    print(lab + ": " + row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [13]:
# menambah kolom menggunakan loc
for lab,row in brics.iterrows():
    brics.loc[:,"country_name_length"] = len(row["country"])

display(brics)

country    capital    area  population  country_name_length
BR        Brazil   Brasilia   8.516      200.40                   12
RU        Russia     Moscow  17.100      143.50                   12
IN         India  New Delhi   3.286     1252.00                   12
CH         China    Beijing   9.597     1357.00                   12
SA  South Africa   Pretoria   1.221       52.98                   12

In [14]:
# menambhkan kolom tanpa looping
brics["country_upper"] = brics["country"].apply(str.upper)

display(brics)

country    capital    area  population  country_name_length  \
BR        Brazil   Brasilia   8.516      200.40                   12   
RU        Russia     Moscow  17.100      143.50                   12   
IN         India  New Delhi   3.286     1252.00                   12   
CH         China    Beijing   9.597     1357.00                   12   
SA  South Africa   Pretoria   1.221       52.98                   12   

   country_upper  
BR        BRAZIL  
RU        RUSSIA  
IN         INDIA  
CH         CHINA  
SA  SOUTH AFRICA